// packages/plugin-annotation/src/vue/components/preview-renderer.vue
<template>
  <div :style="style">
    <Circle
      v-if="preview.type === PdfAnnotationSubtype.CIRCLE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Square
      v-else-if="preview.type === PdfAnnotationSubtype.SQUARE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Polygon
      v-else-if="preview.type === PdfAnnotationSubtype.POLYGON"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Polyline
      v-else-if="preview.type === PdfAnnotationSubtype.POLYLINE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Line
      v-else-if="preview.type === PdfAnnotationSubtype.LINE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Ink
      v-else-if="preview.type === PdfAnnotationSubtype.INK"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <div
      v-else-if="preview.type === PdfAnnotationSubtype.FREETEXT"
      :style="{
        width: '100%',
        height: '100%',
        border: `1px dashed ${preview.data.fontColor || '#000000'}`,
        backgroundColor: 'transparent',
      }"
    />
    <component
      v-else-if="customMatch?.renderPreview"
      :is="customMatch.renderPreview"
      :data="preview.data"
      :bounds="preview.bounds"
      :scale="scale"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, CSSProperties } from 'vue';
import { PreviewState } from '@embedpdf/plugin-annotation';
import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode } from '@embedpdf/models';
import { Circle, Square, Polygon, Polyline, Line, Ink } from './annotations';
import { useRendererRegistry } from '../context/renderer-registry';

const props = defineProps<{
  toolId: string;
  preview: PreviewState;
  scale: number;
}>();

const registry = useRendererRegistry();
const customMatch = computed(
  () => registry?.getAll().find((r) => r.id === props.toolId && r.renderPreview) ?? null,
);

const style = computed<CSSProperties>(() => {
  const base: CSSProperties = {
    position: 'absolute',
    left: `${props.preview.bounds.origin.x * props.scale}px`,
    top: `${props.preview.bounds.origin.y * props.scale}px`,
    width: `${props.preview.bounds.size.width * props.scale}px`,
    height: `${props.preview.bounds.size.height * props.scale}px`,
    pointerEvents: 'none',
    zIndex: 10,
  };

  if (props.preview.type === PdfAnnotationSubtype.INK) {
    base.mixBlendMode = blendModeToCss(props.preview.data.blendMode ?? PdfBlendMode.Normal);
  }

  return base;
});
</script>

// packages/plugin-annotation/src/svelte/components/PreviewRenderer.svelte
<script lang="ts">
  import type { PreviewState } from '@embedpdf/plugin-annotation';
  import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode } from '@embedpdf/models';
  import Circle from './annotations/Circle.svelte';
  import Square from './annotations/Square.svelte';
  import Polygon from './annotations/Polygon.svelte';
  import Polyline from './annotations/Polyline.svelte';
  import Line from './annotations/Line.svelte';
  import Ink from './annotations/Ink.svelte';
  import { getRendererRegistry } from '../context/renderer-registry.svelte';

  interface PreviewRendererProps {
    toolId: string;
    preview: PreviewState;
    scale: number;
  }

  let { toolId, preview, scale }: PreviewRendererProps = $props();

  const registry = getRendererRegistry();

  const bounds = $derived(preview.bounds);

  const style = $derived({
    left: bounds.origin.x * scale,
    top: bounds.origin.y * scale,
    width: bounds.size.width * scale,
    height: bounds.size.height * scale,
  });
</script>

{#if preview.type === PdfAnnotationSubtype.CIRCLE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Circle isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.SQUARE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Square isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.POLYGON}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Polygon isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.POLYLINE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Polyline isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.LINE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Line isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.INK}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
    style:mix-blend-mode={blendModeToCss(preview.data.blendMode ?? PdfBlendMode.Normal)}
  >
    <Ink isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.FREETEXT}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <div
      style:width="100%"
      style:height="100%"
      style:border="1px dashed {preview.data.fontColor || '#000000'}"
      style:background-color="transparent"
    ></div>
  </div>
{:else}
  {@const match = registry?.getAll().find((r) => r.id === toolId && r.renderPreview)}
  {#if match?.renderPreview}
    {@const PreviewComponent = match.renderPreview}
    <div
      style:position="absolute"
      style:left="{style.left}px"
      style:top="{style.top}px"
      style:width="{style.width}px"
      style:height="{style.height}px"
      style:pointer-events="none"
      style:z-index="10"
    >
      <PreviewComponent data={preview.data} bounds={preview.bounds} {scale} />
    </div>
  {/if}
{/if}
