// packages/plugin-annotation/src/shared/components/annotations/free-text.tsx
import {
  MouseEvent,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  suppressContentEditableWarningProps,
} from '@framework';
import {
  PdfFreeTextAnnoObject,
  PdfVerticalAlignment,
  standardFontCssProperties,
  textAlignmentToCss,
} from '@embedpdf/models';
import { useAnnotationCapability } from '../..';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';

interface FreeTextProps {
  documentId: string;
  isSelected: boolean;
  isEditing: boolean;
  annotation: TrackedAnnotation<PdfFreeTextAnnoObject>;
  pageIndex: number;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement>) => void;
  onDoubleClick?: (event: MouseEvent<HTMLDivElement>) => void;
  /** When true, AP canvas provides the visual; hide text content */
  appearanceActive?: boolean;
}

export function FreeText({
  documentId,
  isSelected,
  isEditing,
  annotation,
  pageIndex,
  scale,
  onClick,
  appearanceActive = false,
}: FreeTextProps) {
  const editorRef = useRef<HTMLSpanElement>(null);
  const editingRef = useRef(false);
  const { provides: annotationCapability } = useAnnotationCapability();
  const annotationProvides = annotationCapability?.forDocument(documentId) ?? null;
  const [isIOS, setIsIOS] = useState(false);

  useEffect(() => {
    if (isEditing && editorRef.current) {
      editingRef.current = true;
      const editor = editorRef.current;
      editor.focus();

      const tool = annotationProvides?.findToolForAnnotation(annotation.object);
      const isDefaultContent =
        tool?.defaults?.contents != null && annotation.object.contents === tool.defaults.contents;

      const selection = window.getSelection();
      if (selection) {
        const range = document.createRange();
        range.selectNodeContents(editor);
        if (!isDefaultContent) {
          range.collapse(false);
        }
        selection.removeAllRanges();
        selection.addRange(range);
      }
    }
  }, [isEditing]);

  useLayoutEffect(() => {
    try {
      const nav = navigator as any;
      const ios =
        /iPad|iPhone|iPod/.test(navigator.userAgent) ||
        (navigator.platform === 'MacIntel' && nav?.maxTouchPoints > 1);
      setIsIOS(ios);
    } catch {
      setIsIOS(false);
    }
  }, []);

  const handleBlur = () => {
    if (!editingRef.current) return;
    editingRef.current = false;
    if (!annotationProvides) return;
    if (!editorRef.current) return;
    annotationProvides.updateAnnotation(pageIndex, annotation.object.id, {
      contents: editorRef.current.innerText.replace(/\u00A0/g, ' '),
    });
  };

  // iOS zoom prevention: keep focused font-size >= 16px, visually scale down if needed.
  const computedFontPx = annotation.object.fontSize * scale;
  const MIN_IOS_FOCUS_FONT_PX = 16;
  const needsComp =
    isIOS && isEditing && computedFontPx > 0 && computedFontPx < MIN_IOS_FOCUS_FONT_PX;
  const adjustedFontPx = needsComp ? MIN_IOS_FOCUS_FONT_PX : computedFontPx;
  const scaleComp = needsComp ? computedFontPx / MIN_IOS_FOCUS_FONT_PX : 1;
  const invScalePercent = needsComp ? 100 / scaleComp : 100;

  return (
    <div
      style={{
        position: 'absolute',
        width: annotation.object.rect.size.width * scale,
        height: annotation.object.rect.size.height * scale,
        cursor: isSelected && !isEditing ? 'move' : 'default',
        pointerEvents: isSelected && !isEditing ? 'none' : 'auto',
        zIndex: 2,
        opacity: appearanceActive ? 0 : 1,
      }}
      onPointerDown={onClick}
    >
      <span
        ref={editorRef}
        onBlur={handleBlur}
        tabIndex={0}
        style={{
          color: annotation.object.fontColor,
          fontSize: adjustedFontPx,
          ...standardFontCssProperties(annotation.object.fontFamily),
          textAlign: textAlignmentToCss(annotation.object.textAlign),
          flexDirection: 'column',
          justifyContent:
            annotation.object.verticalAlign === PdfVerticalAlignment.Top
              ? 'flex-start'
              : annotation.object.verticalAlign === PdfVerticalAlignment.Middle
                ? 'center'
                : 'flex-end',
          display: 'flex',
          backgroundColor: annotation.object.color ?? annotation.object.backgroundColor,
          opacity: annotation.object.opacity,
          width: needsComp ? `${invScalePercent}%` : '100%',
          height: needsComp ? `${invScalePercent}%` : '100%',
          lineHeight: '1.18',
          overflow: 'hidden',
          cursor: isEditing ? 'text' : 'pointer',
          outline: 'none',
          transform: needsComp ? `scale(${scaleComp})` : undefined,
          transformOrigin: 'top left',
        }}
        contentEditable={isEditing}
        {...suppressContentEditableWarningProps}
      >
        {annotation.object.contents}
      </span>
    </div>
  );
}

// packages/plugin-annotation/src/vue/components/annotations/free-text.vue
<template>
  <div
    :style="{
      position: 'absolute',
      width: `${annotation.object.rect.size.width * scale}px`,
      height: `${annotation.object.rect.size.height * scale}px`,
      cursor: isSelected && !isEditing ? 'move' : 'default',
      pointerEvents: isSelected && !isEditing ? 'none' : 'auto',
      zIndex: 2,
      opacity: appearanceActive ? 0 : 1,
    }"
    @pointerdown="onClick"
  >
    <span
      ref="editorRef"
      @blur="handleBlur"
      tabindex="0"
      :style="editorStyle"
      :contenteditable="isEditing"
      >{{ annotation.object.contents }}</span
    >
  </div>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { ref, watch, computed, onMounted, nextTick } from 'vue';
import {
  PdfFreeTextAnnoObject,
  PdfVerticalAlignment,
  standardFontCssProperties,
  textAlignmentToCss,
} from '@embedpdf/models';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';
import { useAnnotationCapability } from '../../hooks';

const props = withDefaults(
  defineProps<{
    documentId: string;
    isSelected: boolean;
    isEditing: boolean;
    annotation: TrackedAnnotation<PdfFreeTextAnnoObject>;
    pageIndex: number;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    appearanceActive?: boolean;
  }>(),
  {
    appearanceActive: false,
  },
);

const editorRef = ref<HTMLSpanElement | null>(null);
const editingRef = ref(false);
const { provides: annotationCapability } = useAnnotationCapability();
const annotationProvides = computed(
  () => annotationCapability.value?.forDocument(props.documentId) ?? null,
);
const isIOS = ref(false);

onMounted(() => {
  try {
    const nav = navigator as any;
    isIOS.value =
      /iPad|iPhone|iPod/.test(navigator.userAgent) ||
      (navigator.platform === 'MacIntel' && nav?.maxTouchPoints > 1);
  } catch {
    isIOS.value = false;
  }
});

watch(
  () => props.isEditing,
  async (editing) => {
    if (!editing) return;
    await nextTick();
    if (!editorRef.value) return;
    editingRef.value = true;
    const editor = editorRef.value;
    editor.focus();

    const tool = annotationProvides.value?.findToolForAnnotation(props.annotation.object);
    const isDefaultContent =
      tool?.defaults?.contents != null &&
      props.annotation.object.contents === tool.defaults.contents;

    const selection = window.getSelection();
    if (selection) {
      const range = document.createRange();
      range.selectNodeContents(editor);
      if (!isDefaultContent) {
        range.collapse(false);
      }
      selection.removeAllRanges();
      selection.addRange(range);
    }
  },
  { immediate: true },
);

const handleBlur = () => {
  if (!editingRef.value) return;
  editingRef.value = false;
  if (!annotationProvides.value || !editorRef.value) return;
  annotationProvides.value.updateAnnotation(props.pageIndex, props.annotation.object.id, {
    contents: editorRef.value.innerText.replace(/\u00A0/g, ' '),
  });
};

const editorStyle = computed(() => {
  const { object: anno } = props.annotation;
  const computedFontPx = anno.fontSize * props.scale;
  const MIN_IOS_FOCUS_FONT_PX = 16;
  const needsComp =
    isIOS.value && props.isEditing && computedFontPx > 0 && computedFontPx < MIN_IOS_FOCUS_FONT_PX;
  const adjustedFontPx = needsComp ? MIN_IOS_FOCUS_FONT_PX : computedFontPx;
  const scaleComp = needsComp ? computedFontPx / MIN_IOS_FOCUS_FONT_PX : 1;
  const invScalePercent = needsComp ? 100 / scaleComp : 100;

  return {
    color: anno.fontColor,
    fontSize: `${adjustedFontPx}px`,
    ...standardFontCssProperties(anno.fontFamily),
    textAlign: textAlignmentToCss(anno.textAlign),
    flexDirection: 'column' as 'column',
    justifyContent:
      anno.verticalAlign === PdfVerticalAlignment.Top
        ? 'flex-start'
        : anno.verticalAlign === PdfVerticalAlignment.Middle
          ? 'center'
          : 'flex-end',
    display: 'flex',
    backgroundColor: anno.color ?? anno.backgroundColor,
    opacity: anno.opacity,
    width: needsComp ? `${invScalePercent}%` : '100%',
    height: needsComp ? `${invScalePercent}%` : '100%',
    lineHeight: '1.18',
    overflow: 'hidden',
    cursor: props.isEditing ? 'text' : 'pointer',
    outline: 'none',
    transform: needsComp ? `scale(${scaleComp})` : undefined,
    transformOrigin: 'top left',
  };
});
</script>
